CocoaKeyDownLib
---------------

CocoaKeyDownLib consists of two Swift files: an extension on ``NSModifierFlags``, and an extension on ``NSEvent``. Together, the two files are designed to simplify the interrogation of events generated by user key-presses. Given an ``NSEvent``, the API is designed to provide answers to questions like:

- Is the [INSERT MODIFIER] key **the only** modifier key that is being pressed?
- Is the [INSERT MODIFIER] key **among** the modifier keys being pressed?

In addition, you can query the event looking for a specific combination of modifiers and characters:

- Is the user pressing [Shift]+[Alt]+[S]?
- Is the user pressing the [Down-Arrow] in the absence of any modifiers?

The API is largely self-documenting, though additional information is provided via Xcode-friendly markup. To access this information, position the cursor over the relevant method and [Alt]-Click.


Getting it into your project
----------------------------
Swift support for stand-alone libraries and frameworks is limited at the moment (27th Jan. 2015), so the files have not been incorporated into any such structure. To use, simply copy the files into your projects.

